### ISSUE TITLE
Run Local Tests Light not turning green

### ISSUE THREAD

**Issue by vinay0410** [learn-co-curriculum/objc-palindrome-inspector#3]
![screen shot 2016-03-27 at 1 50 31 pm](https://cloud.githubusercontent.com/assets/18044818/14064493/eef9fbd6-f422-11e5-8b93-6f0a7faaa46c.png)
All the test are passed as you can see but the same isn't reflected in the learn.co lesson page

**Comment by AnnJohn** [comment]
sorry for the delay @vinay0410. Since this is a technical problem, can you please file a bug report? If yoi hover over your profile pic in Learn, you'll see an option to report a bug. thanks!
