### ISSUE TITLE
local build not going green 

### ISSUE THREAD

**Issue by zainnadeem** [learn-co-curriculum/objc-palindrome-inspector#5]
I have all of the tests succeeding but the local build light will not go green. I tried closing my browser and quitting the learn app but the issue persists.

**Comment by hannachoi** [comment]
I am having the same issue! All my tests have succeeded but the 'local build' / 'run local tests' light hasn't turned green. The light for submitting my pull request did turn green though. Please let me know what I can do!
<img width="902" alt="screenshot xcode" src="https://cloud.githubusercontent.com/assets/17521086/14584926/657fbb8c-042d-11e6-98f8-9ba219173da4.png">
![screenshot learn](https://cloud.githubusercontent.com/assets/17521086/14584927/65805a2e-042d-11e6-874c-ef2d3986a166.png)

**Comment by AnnJohn** [comment]
hi @zainnadeem and @hannachoi, can you please submit bug reports for this (if you hover over your profile pic in Learn, you'll see a menu with an option to file a bug report). We use this space for issues specific to the content of the curriculum, but thank you regardless for pointing this out.

**Comment by hannachoi** [comment]
Thanks @AnnJohn!
